"""Add direction to user

Revision ID: 01120c9588a2
Revises: 1c9a59718705
Create Date: 2026-04-09 21:32:13.133359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01120c9588a2'
down_revision: Union[str, None] = '1c9a59718705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('direction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'directions', ['direction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'direction_id')
    # ### end Alembic commands ###
