"""Add rejection_reason to requests

Revision ID: 0e211486a087
Revises: ceece0b07b2f
Create Date: 2026-04-09 10:12:51.772310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e211486a087'
down_revision: Union[str, None] = 'ceece0b07b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'rejection_reason')
    # ### end Alembic commands ###
