"""Add file_path to requests

Revision ID: 1530fbdd8ae2
Revises: e83be0af7364
Create Date: 2026-04-08 19:06:54.271310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1530fbdd8ae2'
down_revision: Union[str, None] = 'e83be0af7364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'file_path')
    # ### end Alembic commands ###
