"""add_prefix_to_organizations_and_request_number

Revision ID: 1a84d220a035
Revises: dcbc87546382
Create Date: 2026-04-21 09:50:58.548759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a84d220a035'
down_revision: Union[str, None] = 'dcbc87546382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('prefix', sa.String(length=10), nullable=True))
    op.add_column('payment_requests', sa.Column('request_number', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'payment_requests', ['request_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_requests', type_='unique')
    op.drop_column('payment_requests', 'request_number')
    op.drop_column('organizations', 'prefix')
    # ### end Alembic commands ###
