"""Add inn to organization

Revision ID: 368fedc032a9
Revises: a4bda7ba2158
Create Date: 2026-04-10 10:48:03.263642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368fedc032a9'
down_revision: Union[str, None] = 'a4bda7ba2158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('inn', sa.String(length=12), nullable=True))
    op.drop_constraint('organizations_name_key', 'organizations', type_='unique')
    op.drop_constraint('payment_groups_name_key', 'payment_groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('payment_groups_name_key', 'payment_groups', ['name'])
    op.create_unique_constraint('organizations_name_key', 'organizations', ['name'])
    op.drop_column('organizations', 'inn')
    # ### end Alembic commands ###
