"""Add RBAC structure

Revision ID: 692b91ac18be
Revises: 368fedc032a9
Create Date: 2026-04-10 11:50:36.473846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692b91ac18be'
down_revision: Union[str, None] = '368fedc032a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.add_column('roles', sa.Column('color', sa.String(), nullable=True))
    op.drop_index('ix_roles_name', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('ix_roles_name', 'roles', ['name'], unique=True)
    op.drop_column('roles', 'color')
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
