"""Add calendar engine

Revision ID: 97e823419949
Revises: 3d098036abf2
Create Date: 2026-04-09 14:31:18.916142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e823419949'
down_revision: Union[str, None] = '3d098036abf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_type_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.Column('allowed_category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_type', 'allowed_category', name='_type_category_uc')
    )
    op.create_index(op.f('ix_day_type_rules_day_type'), 'day_type_rules', ['day_type'], unique=False)
    op.create_table('payment_calendar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payment_group_id', sa.UUID(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['payment_group_id'], ['payment_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'payment_group_id', name='_date_group_uc')
    )
    op.create_index(op.f('ix_payment_calendar_date'), 'payment_calendar', ['date'], unique=False)
    op.create_table('weekly_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_group_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['payment_group_id'], ['payment_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_group_id', 'day_of_week', name='_group_day_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_templates')
    op.drop_index(op.f('ix_payment_calendar_date'), table_name='payment_calendar')
    op.drop_table('payment_calendar')
    op.drop_index(op.f('ix_day_type_rules_day_type'), table_name='day_type_rules')
    op.drop_table('day_type_rules')
    # ### end Alembic commands ###
