"""add_is_active_to_nsi_tables

Revision ID: c9cc1d687dc6
Revises: 9a847204f8d9
Create Date: 2026-04-10 20:45:52.165140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cc1d687dc6'
down_revision: Union[str, None] = '9a847204f8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('directions', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('payment_groups', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.drop_column('payment_groups', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_groups', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('payment_groups', 'is_active')
    op.drop_column('organizations', 'is_active')
    op.drop_column('directions', 'is_active')
    op.drop_column('clusters', 'is_active')
    # ### end Alembic commands ###
