"""Add file_path to requests

Revision ID: ceece0b07b2f
Revises: 1530fbdd8ae2
Create Date: 2026-04-08 19:09:27.862474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceece0b07b2f'
down_revision: Union[str, None] = '1530fbdd8ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
