"""Update request and user models

Revision ID: eb2f4154e573
Revises: 97e823419949
Create Date: 2026-04-09 14:36:34.649570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2f4154e573'
down_revision: Union[str, None] = '97e823419949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('payment_requests', sa.Column('direction_id', sa.UUID(), nullable=False))
    op.add_column('payment_requests', sa.Column('budget_item_id', sa.UUID(), nullable=False))
    op.add_column('payment_requests', sa.Column('counterparty', sa.String(), nullable=False))
    op.add_column('payment_requests', sa.Column('contract_status', sa.Boolean(), nullable=True))
    op.add_column('payment_requests', sa.Column('feo_note', sa.String(), nullable=True))
    op.add_column('payment_requests', sa.Column('special_order', sa.Boolean(), nullable=True))
    op.add_column('payment_requests', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('payment_requests', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('payment_requests', sa.Column('payment_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'payment_requests', 'budget_items', ['budget_item_id'], ['id'])
    op.create_foreign_key(None, 'payment_requests', 'directions', ['direction_id'], ['id'])
    op.create_foreign_key(None, 'payment_requests', 'organizations', ['organization_id'], ['id'])
    op.drop_column('payment_requests', 'status')
    op.add_column('users', sa.Column('direction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'directions', ['direction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'direction_id')
    op.add_column('payment_requests', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payment_requests', type_='foreignkey')
    op.drop_constraint(None, 'payment_requests', type_='foreignkey')
    op.drop_constraint(None, 'payment_requests', type_='foreignkey')
    op.drop_column('payment_requests', 'payment_status')
    op.drop_column('payment_requests', 'approval_status')
    op.drop_column('payment_requests', 'priority')
    op.drop_column('payment_requests', 'special_order')
    op.drop_column('payment_requests', 'feo_note')
    op.drop_column('payment_requests', 'contract_status')
    op.drop_column('payment_requests', 'counterparty')
    op.drop_column('payment_requests', 'budget_item_id')
    op.drop_column('payment_requests', 'direction_id')
    op.drop_column('payment_requests', 'organization_id')
    # ### end Alembic commands ###
